//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_AppData_Local_Temp_0469D607FEDEF564FDC04BBE00875CA82E6D_3_TOURDL_TOURDL_Views_Login_Authen_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_AppData_Local_Temp_0469D607FEDEF564FDC04BBE00875CA82E6D_3_TOURDL_TOURDL_Views_Login_Authen_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Admin\AppData\Local\Temp\0469D607FEDEF564FDC04BBE00875CA82E6D\3\TOURDL\TOURDL\Views\Login\Authen.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Admin\AppData\Local\Temp\0469D607FEDEF564FDC04BBE00875CA82E6D\3\TOURDL\TOURDL\Views\Login\Authen.cshtml"
  
    Layout = null;


#line default
#line hidden

#line 3 "C:\Users\Admin\AppData\Local\Temp\0469D607FEDEF564FDC04BBE00875CA82E6D\3\TOURDL\TOURDL\Views\Login\Authen.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 4 "C:\Users\Admin\AppData\Local\Temp\0469D607FEDEF564FDC04BBE00875CA82E6D\3\TOURDL\TOURDL\Views\Login\Authen.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 5 "C:\Users\Admin\AppData\Local\Temp\0469D607FEDEF564FDC04BBE00875CA82E6D\3\TOURDL\TOURDL\Views\Login\Authen.cshtml"
    using (Html.BeginForm("Authen", "Login", FormMethod.Post))
    {
        

#line default
#line hidden

#line 6 "C:\Users\Admin\AppData\Local\Temp\0469D607FEDEF564FDC04BBE00875CA82E6D\3\TOURDL\TOURDL\Views\Login\Authen.cshtml"
                  __o = Html.TextBoxFor(m=>m.Mail_NV);


#line default
#line hidden

#line 7 "C:\Users\Admin\AppData\Local\Temp\0469D607FEDEF564FDC04BBE00875CA82E6D\3\TOURDL\TOURDL\Views\Login\Authen.cshtml"
                  __o = Html.TextBoxFor(m=>m.MatKhau);


#line default
#line hidden

#line 8 "C:\Users\Admin\AppData\Local\Temp\0469D607FEDEF564FDC04BBE00875CA82E6D\3\TOURDL\TOURDL\Views\Login\Authen.cshtml"
               __o = Html.ValidationMessageFor(m => m.MatKhau);


#line default
#line hidden

#line 9 "C:\Users\Admin\AppData\Local\Temp\0469D607FEDEF564FDC04BBE00875CA82E6D\3\TOURDL\TOURDL\Views\Login\Authen.cshtml"
               __o = Html.AntiForgeryToken();


#line default
#line hidden

#line 10 "C:\Users\Admin\AppData\Local\Temp\0469D607FEDEF564FDC04BBE00875CA82E6D\3\TOURDL\TOURDL\Views\Login\Authen.cshtml"
              
    }

#line default
#line hidden
}
}
}
