//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_AppData_Local_Temp_E3807FC56473B6003AD625B957B4845E0AE0_6_TOURDL_TOURDL_Views_NHANVIENs_DashBoard_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_AppData_Local_Temp_E3807FC56473B6003AD625B957B4845E0AE0_6_TOURDL_TOURDL_Views_NHANVIENs_DashBoard_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Admin\AppData\Local\Temp\E3807FC56473B6003AD625B957B4845E0AE0\6\TOURDL\TOURDL\Views\NHANVIENs\DashBoard.cshtml"
__o = model;


#line default
#line hidden
}
}
}
