//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOURDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int ID_HoaDon { get; set; }
        public Nullable<int> SLTreEm { get; set; }
        public Nullable<int> TongTienTour { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> SLNguoiLon { get; set; }
        public Nullable<int> TienKhuyenMai { get; set; }
        public Nullable<int> TienPhaiTra { get; set; }
        public string ID_SPTour { get; set; }
        public Nullable<int> ID_KH { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual SPTOUR SPTOUR { get; set; }
    }
}
