//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_AppData_Local_Temp_809481DC96A0D4DE683115D2A4D60458FAAF_2_TOURDL_TOURDL_Views_TOURs_Edit_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_AppData_Local_Temp_809481DC96A0D4DE683115D2A4D60458FAAF_2_TOURDL_TOURDL_Views_TOURs_Edit_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
  
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";


#line default
#line hidden

#line 3 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
using (Html.BeginForm())
{
    

#line default
#line hidden

#line 4 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
                            
    
    

#line default
#line hidden

#line 6 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
   __o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 7 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
   __o = Html.HiddenFor(model => model.ID_TOUR);


#line default
#line hidden

#line 8 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
       __o = Html.LabelFor(model => model.TenTour, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 9 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
           __o = Html.EditorFor(model => model.TenTour, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 10 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
           __o = Html.ValidationMessageFor(model => model.TenTour, "", new { @class = "text-danger" });


#line default
#line hidden

#line 11 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
       __o = Html.LabelFor(model => model.GiaTour, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 12 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
           __o = Html.EditorFor(model => model.GiaTour, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 13 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
           __o = Html.ValidationMessageFor(model => model.GiaTour, "", new { @class = "text-danger" });


#line default
#line hidden

#line 14 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
       __o = Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 15 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
           __o = Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 16 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
           __o = Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" });


#line default
#line hidden

#line 17 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
       __o = Html.LabelFor(model => model.HinhTour, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 18 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
           __o = Html.TextBoxFor(model => model.HinhTour, null, new { type="file", @class = "form-control" });


#line default
#line hidden

#line 19 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
           __o = Html.ValidationMessageFor(model => model.HinhTour, "", new { @class = "text-danger" });


#line default
#line hidden

#line 20 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
       __o = Html.LabelFor(model => model.TinhThanh, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 21 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
           __o = Html.EditorFor(model => model.TinhThanh, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 22 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
           __o = Html.ValidationMessageFor(model => model.TinhThanh, "", new { @class = "text-danger" });


#line default
#line hidden

#line 23 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
       __o = Html.LabelFor(model => model.LoaiTour, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 24 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
           __o = Html.EditorFor(model => model.LoaiTour, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 25 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
           __o = Html.ValidationMessageFor(model => model.LoaiTour, "", new { @class = "text-danger" });


#line default
#line hidden

#line 26 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
          
}

#line default
#line hidden

#line 27 "C:\Users\Admin\AppData\Local\Temp\809481DC96A0D4DE683115D2A4D60458FAAF\2\TOURDL\TOURDL\Views\TOURs\Edit.cshtml"
__o = Html.ActionLink("Back to List", "Index");


#line default
#line hidden
}
}
}
